spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://elegant.kro.kr:3306/elegantChildren?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 948608093274-1g12niauejkfgbdg2qot01d6fb2doahp.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://elegant.kro.kr/login/oauth2/code/google
          kakao:
            client-id: daf061e4c4faaddcdf107de1cb3e50a7
            client-secret: JkFMWHc5iqkpaQDgyQOKJFmCp0hyfpRN
            redirect-uri: http://elegant.kro.kr/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, profile_nickname, account_email
            client-name: Kakao
          naver:
            client-id: EX_qwVyZ4ucutTR4cWqf
            client-secret: tY9F3gyaXj
            scope: profile_image, name, email
            authorization-grant-type: authorization_code
            redirect-uri: http://elegant.kro.kr/login/oauth2/code/naver
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


server:
  ssl:
    key-store: classpath:BOOT-INF/classes/keystore.p12
    key-store-password: 1q2w3e4r
    key-store-type: PKCS12
    enabled: true
  tomcat:
     max-http-form-post-size: 128MB

