spring:
  profiles:
    include: production
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
logging:
  level:
    org.hibernate.sql: debug

jwt:
  secretKey: as2189d1o2mocqem31x1c3o34m3c4owlkf13orm134oirmt134oitm341i1io34tm43i1om12o4fim059gk0259g4m
  token:
    # 3 hours
    expiration: 10000000
    header: Authorization

openapi:
  key: 426e594f5673737338366a70714f68





