spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elegantChildren?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1059461192535-c8giu285cbt1fkokf1bbtnpojsd7lru2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            client-id: d0f9461cc37d2b5858adb61ef61b4571
            client-secret: MPPQaMStpmo3C1Mc5xbTMopapmtzLeLC
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, profile_nickname, account_email
            client-name: Kakao
          naver:
            client-id: ZT6DC2RHoiOh0nck6y9P
            client-secret: pRAcRLFSL_
            scope: profile_image, name, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:elegantchildren-57034633fedb.json
        #          location: classpath:elegantchildren-57034633fedb.json
        #          location: src/main/resources/elegantchildren-57034633fedb.json
        project-id: elegantchildren
        bucket: elegant-bucket

